sudo: required

secure: "lEVyZgxclUsibDGZwBZOb0sa7raIT2M8AMvnULh7OhhsQPmWD0uinpaz3clk9H94kEM64Gib9rYPmk4GnhdLNeJH7rSegwf7AB50Ah2JxwdTQrsTRbdedMVzeZ8pePtR8XIF4JiBzyoUahKpzcVOFmohmGtwRP0DcNFPxxV+YvNMrHQgUw+W7HhU1gfPnGBekoLOH+IR+YebVCWo1N34/K3gioDmCFUfDywB7NzILueJj52/ReOFtsug4hxHP+i0KMkQJktIH5NYu8zUyDfibYnQiQHn76ogcsTSEIof6dJj5bFOTST/ow57yDjZkyQSBSnfYDdid/Atx6TMszN0MvXQuEykrDkWFnuvA7YH3zL7NtVmf/paTB1AnbInH27jCp9FBAgvN60TroKiE2ks8Ye8rc0yvQTbu6pD50+1F9EvwVBAhnMosy8zUJBIoozouRpRVXqaNP6m/FvnNuZ5nqaFyJbcbUuM1SQp2GYGcayl8D8MkpzlN21Q9U3kEhegN/bpoXGL8QqQJr4YHPzK20q/m27u1k1HgRxNtHqPS6gN289mrbmhrigKdB0Lmb6SlacSmcpUkndYxtcLdU5BMN+OQHoNFgX3dxdmPCtQhMjpZ+TQHlSNayn7Iy+dRZ/DaXFQnnWJDoKxjU0uXB4GH6xMZIg97XmQBYkp2lsMAEo="

env:
    - PORT=8888
    - SMOGON_DNS="smogon"

services:
    - docker

before_script:
    - docker-compose up -d --build

script:
    - docker-compose exec bot pytest

after_script:
    - docker-compose down
