version: '3'
services:
  bot:
    build:
      context: bot/
      dockerfile: Dockerfile
    environment:
        - "TOKEN=${TOKEN}"
        - COMMON_PORT=8888
        - SMOGON_DNS=smogon
        - FRINKIAC_DNS=frinkiac
    restart: always
    container_name: bot

  smogon:
    build:
        context: smogon/
        dockerfile: Dockerfile
    environment:
        - PORT=8888
    expose:
        - 8888
    restart: always
    container_name: smogon

  frinkiac:
    build:
      context: frinkiac/
      dockerfile: Dockerfile
    environment:
      - PORT=8888
    expose:
      - 8888
    restart: always
    container_name: frinkiac