version: '3'
services:
  bot:
    build:
      context: docker/bot/
      dockerfile: Dockerfile
    environment:
        - "TOKEN=${TOKEN}"
        - COMMON_PORT=8888
        - SMOGON_DNS=smogon
    restart: always
    container_name: bot

  smogon:
    build:
        context: docker/smogon/
        dockerfile: Dockerfile
    environment:
        - PORT=8888
    expose:
        - 8888
    restart: always
    container_name: smogon
