version: '3'
services:
  bot:
    build:
      context: docker/bot/
      dockerfile: Dockerfile
    environment:
        - "TOKEN=${TOKEN}"
        - "COMMON_PORT=${PORT}"
        - "SMOGON_DNS=${SMOGON_DNS}"
    restart: always
    container_name: bot

  smogon:
    build:
        context: docker/smogon/
        dockerfile: Dockerfile
    environment:
        - "PORT=${PORT}"
    expose:
        - "${PORT}"
    restart: always
    container_name: "${SMOGON_DNS}"
