version: '3'
services:
  bot:
    build:
      context: bot/
      dockerfile: Dockerfile
    environment:
        - "TOKEN=${TOKEN}"
        - COMMON_PORT=8888
        - SMOGON_DNS=smogon
        - IMAGE_DIR=images
        - DEEPFRY_DNS=deepfrier
        - DEEPFRY_DIR=./deepfried
    volumes:
        - deepfry_volume:/usr/src/app/deepfried
    restart: always
    container_name: bot

  smogon:
    build:
        context: smogon/
        dockerfile: Dockerfile
    environment:
        - PORT=8888
    expose:
        - 8888
    restart: always
    container_name: smogon

  deepfrier:
    build:
      context: deepfrier/
      dockerfile: Dockerfile
    environment:
        - PORT=8888
        - DEEPFRY_DIR=./deepfried
    expose:
        - 8888
    volumes:
        - deepfry_volume:/home/node/app/deepfried
    restart: always
    container_name: deepfrier

volumes:
  deepfry_volume: