version: '3'
services:
  bot:
    build:
      context: bot/
      dockerfile: Dockerfile
    environment:
        - "TOKEN=${TOKEN}"
        - SMOGON_DNS=smogon
        - SMOGON_PORT=8888
    restart: always
    container_name: bot

  smogon:
    build:
        context: smogon/
        dockerfile: Dockerfile
    environment:
        - PORT=8888
    expose:
        - 8888
    restart: always
    container_name: smogon